### ISSUE TITLE
'Barebones' Could not be found 'UINetworkRoom' Could Not Be found

### ISSUE THREAD

**Issue by dustinmckay** [insthync/ShooterIOMasterServer#2]
Brand new import of the latest release package. Unity 2017.3.0f3
I get three errors regarding UIMainMenuMsk.cs(4,7): Error CS0246: The type of namespace name 'Barebones' could not be found. Are you missing an assembly references......

**Comment by insthync** [comment]
You have to import this package https://www.assetstore.unity3d.com/en/#!/content/71391
